apiVersion: v1
kind: Pod
metadata:
  name: client-pod
spec:
  containers:
  - name: client
    image: nicolaka/netshoot
    command: [ "sleep", "infinity" ]
    securityContext:
      capabilities:
        add: ["NET_ADMIN", "NET_RAW"]

